config/routes.rb
Yegfilm::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  get "profiles/index"
  resources :profiles
  root to: 'profiles#index'

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user

	has_attached_file :picture, 
	styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

    # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(current_user.id)
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :picture, :description, :availability, :editing, :camera, :sound, :writing, :animation, :acting, :lighting, :grip, :music, :photography, :artdept, :locations, :directing, :producing, :setops, :hair, :wardrobe, :food, :skills, :projects, :contact)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/profiles/new'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yegfilm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=1.0, initial-scale=1" />
	
	<link href='http://fonts.googleapis.com/css?family=Cabin:400,500,700' rel='stylesheet' type='text/css'>
	
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50622799-1', 'yegfilm.herokuapp.com');
  ga('send', 'pageview');

</script>
</head>
<body>
	<div class="photo-box">
	</div>
	
	<% if params[:action] != 'new' %>
	
	<nav class="top-bar">
		<ul class="left">
			<li>
				<h2>
				<%= link_to '#yegfilm', profiles_path %> <span class="alpha">Alpha</span>
				</h2>
			</li>
		</ul>

		<ul class ="right">
			<% if user_signed_in? %>
				<li>
	  			Hi, <%= current_user.email %>!
				</li>
				<li>			
					<a href="/profiles/<%= current_user.id%>"><i class="fa fa-user"></i> View my Profile</a>
				</li>
				<li>
					 <a href="/profiles/<%= current_user.id%>/edit"><i class="fa fa-pencil-square"></i> Edit my Profile</a>
				</li>
				<li>
	  			<i class="fa fa-cog"></i> <%= link_to 'Settings', edit_user_registration_path, :class => 'navbar-link' %> 
				</li>
				<li>
	  			<i class="fa fa-sign-out"></i> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
				</li>
			<% else %>
				<li>
			  	<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
			  </li>
				<li>
				<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
			</li>
			<% end %>
		</ul>
	</nav>

	<%end%>
	
<div class="wrapper row">
		
    

	
<span class="notice"><%= notice %></span>
<span class="alert"><%= alert %></span>
<%= yield %>
</div>
<footer><p><i class="fa fa-bug"></i> Found a bug? Want to request a feature? Email us at info[at]theedmontonianmediaco.com </p>
</body>
</html>

app/views/profiles/_form.html.erb
<div class="row white-bg">
  <div class="small-10 columns">
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <oblique>We don't have a way to host your picture just yet, so for now, just link to an existing picture.</oblique>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <label>Tell us about yourself:</label>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    Check this box if you are currently available to work on projects. Leave it unchecked if you are not. <br>
    <%= f.check_box :availability %>
  </div>

 <div class="field">
   Please select which positions you would be capable of filling on a set.
  <table>
    <tbody>
      <tr>
        <td>
          <%= f.label :editing %><br>
          <%= f.check_box :editing %>
        </td>
        <td>
          <%= f.label :camera %><br>
          <%= f.check_box :camera %>
        </td>
        <td>
          <%= f.label :sound %><br>
          <%= f.check_box :sound %>
        </td>
        <td>
          <%= f.label :writing %><br>
          <%= f.check_box :writing %>
        </td>
        <td>
          <%= f.label :animation %><br>
          <%= f.check_box :animation %>
        </td>
      </tr>
      <tr>
        <td>    
          <%= f.label :lighting %><br>
          <%= f.check_box :lighting %>
        </td>
        <td>
          <%= f.label :grip %><br>
          <%= f.check_box :grip %>
        </td>
        <td>
          <%= f.label :music %><br>
          <%= f.check_box :music %>
        </td>
        <td>
          <%= f.label :photography %><br>
          <%= f.check_box :photography %>
        </td>
        <td>
         <label>Art Department</label><br>
          <%= f.check_box :artdept %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label :locations %><br>
          <%= f.check_box :locations %>
        </td>
        <td>  
          <%= f.label :directing %><br>
          <%= f.check_box :directing %>
        </td>
        <td>  
          <%= f.label :producing %><br>
          <%= f.check_box :producing %>
        </td>
        <td>  
          <label>Set Operations (A.D.)</label><br>
          <%= f.check_box :setops %>
        </td>
        <td>
          <%= f.label :hair %><br>
          <%= f.check_box :hair %>
        </td>
      </tr>
    <tr>
      <td>  
        <%= f.label :wardrobe %><br>
        <%= f.check_box :wardrobe %>
      </td>
      <td>
        <%= f.label :food %><br>
        <%= f.check_box :food %>
      </td>
       <td>
          <%= f.label :acting %><br>
          <%= f.check_box :acting %>
        </td>
    </tr>
</tbody>
</table>
  </div>

  <div class="field">
    <label>Describe your experience level: </label>
  
    <%= f.text_area :skills %>
  </div>


  <div class="field">
    <label>What kind of projects are you interested in working on? (Genre, Length, Paid/unpaid)</label>
    <%= f.text_area :projects %>
  </div>
  <div class="field">
    <label>How can other filmmakers contact you? Specify an email or social media accounts below.</label>
    <%= f.text_area :contact %>
  </div>
  <div class="actions">
    <%= f.submit :class=> 'button' %>
  </div>
<% end %>
</div>
</div>

app/views/profiles/edit.html.erb
<div class="row">
	<div class="small-12 columns">
	<h1>My profile</h1>

<%= render 'form' %>
</div>
</div>

app/views/profiles/index.html.erb
  <div class="row">
    <h1>Yegfilm Directory</h1>
    <h2>Find Edmonton filmmakers!</h2>
  <div id="filters" class="button-group">
    <button class="small" data-filter="*"><strong>Reset List</strong></button>
    <button class="small" data-filter=".camera">Camera</button>
    <button class="small" data-filter=".sound">Sound</button>
    <button class="small" data-filter=".writing">Writing</button>
    <button class="small" data-filter=".animation">Animation</button>
    <button class="small" data-filter=".acting">Acting</button>
    <button class="small" data-filter=".lighting">Lighting</button>
    <button class="small" data-filter=".grip">Grip</button>
    <button class="small" data-filter=".music">Music</button>
    <button class="small" data-filter=".photography">Photography</button>
    <button class="small" data-filter=".artdept">Art Department</button>
    <button class="small" data-filter=".setops">Set Operations</button>
    <button class="small" data-filter=".locations">Locations</button>
    <button class="small" data-filter=".directing">Directing</button>
    <button class="small" data-filter=".producing">Producing</button>
    <button class="small" data-filter=".wardrobe">Wardobe</button>
    <button class="small" data-filter=".food">Food</button>
  </div>

</div>

  <div id="container" class="js-masonry row">
 

    <% @profiles.each do |profile| %>
        <div class="small-12 medium-3 large-3 columns item card 
        <% if profile.camera == true %> camera <%end%> 
        <% if profile.sound==true %> sound<% end %>
        <% if profile.writing==true %> writing<% end %>
        <% if profile.animation == true %> animation <%end%> 
        <% if profile.acting==true %> acting<% end %>
        <% if profile.lighting==true %> lighting<% end %>
        <% if profile.locations==true %> locations<% end %>
        <% if profile.grip == true %> grip <%end%> 
        <% if profile.music==true %> music<% end %>
        <% if profile.photography==true %> photography<% end %>     
        <% if profile.artdept == true %> artdept <%end%> 
        <% if profile.setops==true %> setops<% end %>
        <% if profile.directing==true %> directing<% end %>
        <% if profile.producing == true %> producing <%end%> 
        <% if profile.wardrobe==true %> wardrobe<% end %>
        <% if profile.food==true %> food<% end %>
        ">
          <p>
          <% if profile.availability == true %>
            <div class="availability green"><i class="fa fa-check-circle"></i> Yes, I am currently available for projects</div>
          <% else %>
            <div class="no-availability red"><i class="fa fa-times-circle"></i> No, I am not currently available for projects</div>
          <% end %>

        </p>
        <% if profile.picture? %>
          <img src="<%= profile.picture %>" height="100" width="100"/>
        <% else %>
          <%= image_tag 'avatar.jpg' %>
        <% end%>
        
        <h3><%= profile.name %></h3>
        <strong><%= profile.name %>'s Skills</strong>
        <ul>
          <% if profile.camera == true %>
            <li>Cinematography &amp; Camera Ops</li>
          <% end %>
          <% if profile.sound == true %>
            <li>Sound Recording &amp; Mixing</li>
          <% end %>

          <% if profile.writing == true %>
            <li>Writing</li>
          <% end %>

          <% if profile.animation == true %>
            <li>Motion Graphics &amp;Animation </li>
          <% end %>

          <% if profile.acting  == true %>
            <li>Acting</li>
          <% end %>

          <% if profile.lighting  == true %>
            <li>Lighting</li>
          <% end %>

          <% if profile.grip  == true %>
            <li>Grip</li>
          <% end %>

          <% if profile.music == true %>
            <li>Music</li>
          <% end %>

          <% if profile.photography == true %>
            <li>Still Photography</li>
          <% end %>

          <% if profile.artdept == true %>
            <li>Art Department</li>
          <% end %>

          <% if profile.locations == true %>
            <li>Locations</li>
          <% end %>

          <% if profile.directing == true %>
            <li>Directing</li>
          <% end %>

          <% if profile.producing == true %>
            <li>Producing</li>
          <% end %>

          <% if profile.setops == true %>
            <li>Set Operations</li>
          <% end %>

          <% if profile.hair == true %>
            <li>Hair</li>
          <% end %>

          <% if profile.wardrobe == true %>
            <li>Wardrobe</li>
          <% end %>

          <% if profile.food == true %>
            <li>Food</li>
          <% end %>

        </p>
        
        <%= link_to 'View Profile', profile, :class=>"button small" %>
 
    </div>
    <% end %>

</div>
<br>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

app/views/profiles/show.html.erb
<div class="row white-bg">
  <div class="small-12 columns">
  <% if current_user.id == @profile.id%>
         <i class="fa fa-pencil-square"></i> <%= link_to 'Edit My Profile', edit_profile_path(@profile) %>
  <%end%>
  
    <p id="notice"><%= notice %></p>

    <p>
      
    <p>Current user ID: <%= current_user.id%></p>
    <p>Profile ID: <%= @profile.id %>
    
        <% if @profile.availability == true %>
          <span class="green"><i class="fa fa-check-circle"></i> Yes, I am currently available for projects.</span>
        <% else %>  
          <span class="red"><i class="fa fa-times-circle"></i> No, I am not currently available for projects.</span>
        <% end %>
    </p>

    <h3>
      <%= @profile.name %>
    </h3>
    <% if @profile.picture? %>
      <img src="<%= @profile.picture %>"/>
    <% else %>
      <%= image_tag 'avatar.jpg' %>
    <% end%>
    
    <p>
      <strong>About me:</strong>
      <%= @profile.description %>
    </p>

<strong>My Skills: </strong>
<ul>
  <% if @profile.camera == true %>
    <li>Camera</li>
  <% end %>

  <% if @profile.sound == true %>
    <li>Sound</li>
  <% end %>

  <% if @profile.writing == true %>
    <li>Writing</li>
  <% end %>

  <% if @profile.animation == true %>
    <li>Animation</li>
  <% end %>

  <% if @profile.acting  == true %>
    <li>Acting</li>
  <% end %>

  <% if @profile.lighting  == true %>
    <li>Lighting</li>
  <% end %>

  <% if @profile.grip  == true %>
    <li>Grip</li>
  <% end %>

  <% if @profile.music == true %>
    <li>Music</li>
  <% end %>

  <% if @profile.photography == true %>
    <li>Photograph</li>
  <% end %>

  <% if @profile.artdept == true %>
    <li>Art Department</li>
  <% end %>

  <% if @profile.locations == true %>
    <li>Locations</li>
  <% end %>

  <% if @profile.directing == true %>
    <li>Directing</li>
  <% end %>

  <% if @profile.producing == true %>
    <li>Producing</li>
  <% end %>

  <% if @profile.setops == true %>
    <li>Set Operations (Assistant Director):</li>
  <% end %>

  <% if @profile.hair == true %>
    <li>Hair</li>
  <% end %>

  <% if @profile.wardrobe == true %>
    <li>Wardrobe</li>
  <% end %>

  <% if @profile.food == true %>
    <li>Food</span>
  <% end %>
</ul>

</p>



    <p>
      <strong>My Experience Level:</strong>
      <%= @profile.skills %>
    </p>

    <p>
      <strong>The kinds of projects I'm interested in working on:</strong>
      <%= @profile.projects %>
    </p>

    <p>
      <strong>Contact:</strong>
      <%= @profile.contact %>
    </p>

  </div>
</div>